### ISSUE TITLE
Where the ddseq.sam comes from? 

### ISSUE THREAD

**Issue by wajm** [jkim208/kim-ddSeq-barcode#1]
$ python parseBarcodes-N1.6.1.py ddSeq.sam barcodeBlocks.txt

I'm just wondering what the source of "ddSeq.sam" is.
In my case, I get bcl file after NextSeq run. Which program do you convert this bcl file to ddseq.sam file?

**Comment by jkim208** [comment]
Hi there, 
From the raw bcl files, I ran Illumina's bcl2fastq2 to convert them to fastq.gz files. The software has a helpful user guide. Once you have the fastq files, you can convert them together to the sam format with FastqToSam from Broad's Picard tools.
